#!/usr/bin/env bash

: "${IPA_STATE_DIR:=/var/lib/freeipa-bootstrap}"
: "${IPA_LOCK_FILE:=/run/lock/freeipa-bootstrap.lock}"
: "${STATE_FILE:=}"
: "${STATE_RUN_DIR:=}"
: "${LOCK_FD:=}"

acquire_install_lock() {
    is_install || return 0
    command_exists flock || {
        log_error "flock is required to serialize normal bootstrap executions"
        return 1
    }
    install -d -m 0755 -- "$(dirname "$IPA_LOCK_FILE")"
    exec {LOCK_FD}>"$IPA_LOCK_FILE"
    if ! flock -n "$LOCK_FD"; then
        log_error "another FreeIPA bootstrap execution already holds $IPA_LOCK_FILE"
        return 1
    fi
    printf '%s\n' "$$" >&"$LOCK_FD"
    log_info "acquired bootstrap execution lock: $IPA_LOCK_FILE"
}
release_install_lock() {
    if [[ -n "${LOCK_FD:-}" ]]; then
        flock -u "$LOCK_FD" 2>/dev/null || true
    fi
}

state_init() {
    if ! is_install; then
        return 0
    fi
    ensure_private_directory "$IPA_STATE_DIR" 'bootstrap state directory'
    ensure_private_directory "$IPA_STATE_DIR/runs" 'bootstrap state runs directory'
    STATE_RUN_DIR="$IPA_STATE_DIR/runs/$RUN_ID"
    [[ ! -e "$STATE_RUN_DIR" && ! -L "$STATE_RUN_DIR" ]] || {
        log_error "refusing to reuse an existing or symlinked state run directory: $STATE_RUN_DIR"
        return 1
    }
    install -d -m 0700 -- "$STATE_RUN_DIR" "$STATE_RUN_DIR/backups"
    STATE_FILE="$STATE_RUN_DIR/state.env"
    [[ ! -e "$STATE_FILE" && ! -L "$STATE_FILE" ]] || {
        log_error "refusing to overwrite an existing or symlinked state file: $STATE_FILE"
        return 1
    }
    : > "$STATE_FILE"
    chmod 0600 "$STATE_FILE"
    state_set RUN_ID "$RUN_ID"
    state_set CREATED_AT "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
}

state_set() {
    local key=${1:?state key required}
    local value=${2-}
    local temporary
    [[ -n "$STATE_FILE" ]] || return 0
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || {
        log_error "refusing invalid state key"
        return 1
    }
    [[ ! -L "$STATE_FILE" ]] || {
        log_error "refusing to write through a symlinked state file: $STATE_FILE"
        return 1
    }
    temporary=$(mktemp "$STATE_RUN_DIR/state.XXXXXX")
    chmod 0600 "$temporary"
    if [[ -f "$STATE_FILE" ]]; then
        awk -v key="$key" 'index($0, key "=") != 1 { print }' "$STATE_FILE" > "$temporary"
    fi
    printf '%s=%q\n' "$key" "$value" >> "$temporary"
    mv -f -- "$temporary" "$STATE_FILE"
    chmod 0600 "$STATE_FILE"
}

state_get() {
    local key=${1:?state key required}
    local default=${2-}
    local value=''
    if [[ -n "$STATE_FILE" && -f "$STATE_FILE" ]]; then
        value=$(awk -F= -v key="$key" '$1 == key { value=$0; sub(/^[^=]*=/, "", value) } END { if (value != "") print value }' "$STATE_FILE")
    fi
    if [[ -n "$value" ]]; then
        # State is root-owned and generated by this script; shell decoding is
        # restricted to values written through printf %q above.
        printf -v STATE_VALUE '%b' "$value"
        printf '%s' "$STATE_VALUE"
    else
        printf '%s' "$default"
    fi
}

state_record_backup() {
    local path=${1:?path required}
    local count copy
    [[ -n "$STATE_FILE" ]] || return 0
    count=$(state_get BACKUP_COUNT 0)
    local existing_index existing_path
    for (( existing_index=1; existing_index<=count; existing_index++ )); do
        existing_path=$(state_get "BACKUP_${existing_index}_PATH" '')
        [[ "$existing_path" == "$path" ]] && return 0
    done
    count=$((count + 1))
    copy="$STATE_RUN_DIR/backups/$(basename "$path").$count"
    if [[ -e "$path" ]]; then
        cp -p -- "$path" "$copy"
        chmod 0600 "$copy"
        state_set "BACKUP_${count}_PATH" "$path"
        state_set "BACKUP_${count}_COPY" "$copy"
    else
        state_set "BACKUP_${count}_PATH" "$path"
        state_set "BACKUP_${count}_COPY" ABSENT
    fi
    state_set BACKUP_COUNT "$count"
}

state_restore_current_run_backups() {
    [[ -n "${STATE_FILE:-}" && -f "$STATE_FILE" ]] || return 0
    local count index path copy temporary
    count=$(state_get BACKUP_COUNT 0)
    [[ "$count" =~ ^[0-9]+$ ]] || return 1
    for (( index=count; index>=1; index-- )); do
        path=$(state_get "BACKUP_${index}_PATH" '')
        copy=$(state_get "BACKUP_${index}_COPY" '')
        [[ -n "$path" && -n "$copy" ]] || return 1
        if [[ "$copy" == ABSENT ]]; then
            if [[ -e "$path" || -L "$path" ]]; then
                rm -f -- "$path" || return 1
            fi
            continue
        fi
        [[ -f "$copy" && ! -L "$copy" ]] || return 1
        temporary=$(mktemp "$(dirname "$path")/.bootstrap-restore.XXXXXX")
        chmod 0600 "$temporary"
        cp -p -- "$copy" "$temporary" || { rm -f -- "$temporary"; return 1; }
        atomic_replace_file "$temporary" "$path" || return 1
    done
    log_warn "restored all managed files from the current-run transaction backups"
}

state_mark_resource() {
    local resource=${1:?resource required}
    local status=${2:?status required}
    local normalized=${resource//[^A-Za-z0-9_]/_}
    state_set "RESOURCE_${normalized}" "$status"
}
