#!/usr/bin/env bash

: "${DNS_PROVIDER_LOADED:=false}"
: "${DNS_VALIDATION_SERVER:=}"
: "${EXTERNAL_DNS_STATUS:=not-applicable}"

DNS_PREREQUISITE_RECORDS=()

dns_reverse_zone_list() {
    if declare -F topology_reverse_zones >/dev/null 2>&1; then
        topology_reverse_zones
    else
        printf '%s\n' "${IPA_REVERSE_ZONE%.}"
    fi
}
dns_zone_for_ipv4() {
    local address=${1:-}
    local candidate calculated
    calculated=$(reverse_zone_for_ipv4 "$address") || return 1
    while IFS= read -r candidate; do
        [[ "${candidate,,}" == "${calculated,,}" ]] && {
            printf '%s' "$candidate"
            return 0
        }
    done < <(dns_reverse_zone_list)
    return 1
}

dns_prepare_generated_directory() {
    if [[ -L "$IPA_GENERATED_DIR" || ( -e "$IPA_GENERATED_DIR" && ! -d "$IPA_GENERATED_DIR" ) ]]; then
        log_error "generated DNS output path must be a real directory: $IPA_GENERATED_DIR"
        return 1
    fi
    install -d -m 0750 -- "$IPA_GENERATED_DIR"
    chmod 0750 "$IPA_GENERATED_DIR"
}

dns_prerequisite_records() {
    local host="${IPA_HOSTNAME%.}."
    local reverse_zone
    local reverse_record
    reverse_zone=$(reverse_zone_for_ipv4 "$IPA_IP_ADDRESS")
    reverse_record=$(reverse_record_for_ipv4 "$IPA_IP_ADDRESS")
    DNS_PREREQUISITE_RECORDS=(
        "$host $DNS_TTL IN A $IPA_IP_ADDRESS"
        "$reverse_record.$reverse_zone. $DNS_TTL IN PTR $host"
    )
}

dns_expected_records() {
    local host="${IPA_HOSTNAME%.}."
    local domain="${IPA_DOMAIN%.}."
    dns_prerequisite_records
    DNS_EXPECTED_RECORDS=(
        "${DNS_PREREQUISITE_RECORDS[@]}"
        "ipa-ca.$domain $DNS_TTL IN A $IPA_IP_ADDRESS"
        "_kerberos-master._tcp.$domain $DNS_TTL IN SRV 0 100 88 $host"
        "_kerberos-master._udp.$domain $DNS_TTL IN SRV 0 100 88 $host"
        "_kerberos._tcp.$domain $DNS_TTL IN SRV 0 100 88 $host"
        "_kerberos._udp.$domain $DNS_TTL IN SRV 0 100 88 $host"
        "_kerberos.$domain $DNS_TTL IN TXT \"$IPA_REALM\""
        "_kpasswd._tcp.$domain $DNS_TTL IN SRV 0 100 464 $host"
        "_kpasswd._udp.$domain $DNS_TTL IN SRV 0 100 464 $host"
        "_ldap._tcp.$domain $DNS_TTL IN SRV 0 100 389 $host"
    )
}

dns_print_expected_records() {
    dns_expected_records
    local record
    for record in "${DNS_EXPECTED_RECORDS[@]}"; do
        printf '%s\n' "$record"
    done
}

dns_generate_plan_file() {
    local path=${1:?DNS plan path required}
    local record
    dns_prerequisite_records
    dns_prepare_generated_directory
    [[ "$(dirname "$path")" == "$IPA_GENERATED_DIR" ]] || {
        log_error "DNS prerequisite plan must be written directly under IPA_GENERATED_DIR"
        return 1
    }
    [[ ! -L "$path" ]] || {
        log_error "refusing to write the DNS prerequisite plan through a symlink: $path"
        return 1
    }
    umask 027
    {
        printf '# FreeIPA external DNS prerequisites generated by freeipa-bootstrap\n'
        printf '# These are required before ipa-server-install; FreeIPA generates the remaining system records after installation.\n\n'
        for record in "${DNS_PREREQUISITE_RECORDS[@]}"; do
            printf '%s\n' "$record"
        done
    } > "$path"
    chmod 0640 "$path"
}

dns_query_output() {
    local name=$1
    local type=$2
    local server=''
    if (( $# >= 3 )); then
        server=$3
    else
        server=${DNS_VALIDATION_SERVER:-}
    fi
    local args=(+time=3 +tries=1 +short)
    [[ -n "$server" ]] && args+=("@$server")
    args+=("$name" "$type")
    dig "${args[@]}" 2>/dev/null
}

dns_normalize_srv() {
    local value=$*
    value=$(awk '{$1=$1; print}' <<< "$value")
    local priority weight port target
    read -r priority weight port target <<< "$value"
    printf '%s %s %s %s' "$priority" "$weight" "$port" "$(normalize_fqdn "$target")"
}

dns_normalize_uri() {
    local value=$*
    value=$(awk '{$1=$1; print}' <<< "$value")
    printf '%s' "$value"
}

dns_record_matches() {
    local type=$1
    local expected=$2
    local actual=$3
    case "$type" in
        A|AAAA) [[ "$actual" == "$expected" ]] ;;
        CNAME) [[ "$(normalize_fqdn "$actual")" == "$(normalize_fqdn "$expected")" ]] ;;
        PTR) [[ "$(normalize_fqdn "$actual")" == "$(normalize_fqdn "$expected")" ]] ;;
        SRV) [[ "$(dns_normalize_srv "$actual")" == "$(dns_normalize_srv "$expected")" ]] ;;
        TXT) [[ "$(tr -d '"' <<< "$actual")" == "$(tr -d '"' <<< "$expected")" ]] ;;
        URI) [[ "$(dns_normalize_uri "$actual")" == "$(dns_normalize_uri "$expected")" ]] ;;
        *) return 1 ;;
    esac
}

dns_validate_record_line() {
    local line=$1
    local server=''
    if (( $# >= 2 )); then
        server=$2
    else
        server=${DNS_VALIDATION_SERVER:-}
    fi
    local name ttl class type expected actual
    read -r name ttl class type expected <<< "$line"
    [[ -n "$name" && -n "$type" && -n "$expected" ]] || return 1
    actual=$(dns_query_output "$name" "$type" "$server" || true)
    local value
    while read -r value; do
        [[ -n "$value" ]] || continue
        if dns_record_matches "$type" "$expected" "$value"; then
            return 0
        fi
    done <<< "$actual"
    log_error "DNS mismatch for $name $type via ${server:-system-resolver}; expected '$expected', got '${actual:-<no answer>}'"
    return 1
}

dns_validate_expected_records() {
    local server=''
    if (( $# >= 1 )); then
        server=$1
    else
        server=${DNS_VALIDATION_SERVER:-}
    fi
    dns_expected_records
    local record failures=0
    for record in "${DNS_EXPECTED_RECORDS[@]}"; do
        if ! dns_validate_record_line "$record" "$server"; then
            failures=$((failures + 1))
        fi
    done
    (( failures == 0 ))
}

dns_validate_prerequisite_records() {
    local server=''
    if (( $# >= 1 )); then
        server=$1
    else
        server=${DNS_VALIDATION_SERVER:-}
    fi
    dns_prerequisite_records
    local record failures=0
    for record in "${DNS_PREREQUISITE_RECORDS[@]}"; do
        if ! dns_validate_record_line "$record" "$server"; then
            failures=$((failures + 1))
        fi
    done
    (( failures == 0 ))
}

dns_record_name_in_managed_zones() {
    local name=${1%.}
    local forward_zone=${IPA_DOMAIN,,}
    forward_zone=${forward_zone%.}
    name=${name,,}
    [[ "$name" == "$forward_zone" || "$name" == *".$forward_zone" ]] && return 0
    local reverse_zone
    while IFS= read -r reverse_zone; do
        reverse_zone=${reverse_zone,,}
        reverse_zone=${reverse_zone%.}
        [[ "$name" == "$reverse_zone" || "$name" == *".$reverse_zone" ]] && return 0
    done < <(dns_reverse_zone_list)
    return 1
}

dns_find_generated_record_file() {
    local candidate newest=''
    [[ -d "${IPA_GENERATED_DIR:-}" ]] || {
        printf '%s' ''
        return 0
    }
    for candidate in "$IPA_GENERATED_DIR"/freeipa-dns-records-*.db; do
        [[ -f "$candidate" && ! -L "$candidate" ]] || continue
        if [[ -z "$newest" || "$candidate" -nt "$newest" ]]; then
            newest=$candidate
        fi
    done
    printf '%s' "$newest"
}

dns_validate_records_file() {
    local path=$1
    local server=''
    if (( $# >= 2 )); then
        server=$2
    else
        server=${DNS_VALIDATION_SERVER:-}
    fi
    local failures=0 line name
    [[ -f "$path" && ! -L "$path" ]] || {
        log_error "FreeIPA DNS record file does not exist: $path"
        return 1
    }
    while IFS= read -r line || [[ -n "$line" ]]; do
        line=${line#"${line%%[![:space:]]*}"}
        [[ -z "$line" || "$line" == \#* || "$line" == \;* ]] && continue
        read -r name _ <<< "$line"
        if ! dns_record_name_in_managed_zones "$name"; then
            log_error "FreeIPA DNS record is outside the managed forward/reverse zones: $name"
            failures=$((failures + 1))
            continue
        fi
        if ! dns_validate_record_line "$line" "$server"; then
            failures=$((failures + 1))
        fi
    done < "$path"
    (( failures == 0 ))
}

dns_provider_load() {
    if [[ "$IPA_DNS_MODE" == integrated ]]; then
        DNS_PROVIDER_LOADED=true
        return 0
    fi
    local module
    case "$DNS_PROVIDER" in
        bind9-webmin) module="$SCRIPT_DIR/dns/providers/bind9-webmin/provider.sh" ;;
        existing) module="$SCRIPT_DIR/dns/providers/existing/provider.sh" ;;
        technitium) module="$SCRIPT_DIR/dns/providers/technitium/provider.sh" ;;
        *) log_error "unsupported DNS provider '$DNS_PROVIDER'; implemented external providers are bind9-webmin, technitium, and existing"; return 1 ;;
    esac
    [[ -r "$module" ]] || {
        log_error "DNS provider module is missing: $module"
        return 1
    }
    # shellcheck disable=SC1090
    source "$module"
    DNS_PROVIDER_LOADED=true
}

dns_provider_call() {
    local action=$1
    shift
    local function_name="dns_provider_${action//-/_}"
    declare -F "$function_name" >/dev/null 2>&1 || {
        log_error "DNS provider '$DNS_PROVIDER' does not implement the required operation '$action'"
        return 1
    }
    "$function_name" "$@"
}

dns_integrated_reverse_zone_configure() {
    log_stage integrated-reverse-dns
    local reverse_zone reverse_record host
    reverse_zone=$(reverse_zone_for_ipv4 "$IPA_IP_ADDRESS")
    reverse_record=$(reverse_record_for_ipv4 "$IPA_IP_ADDRESS")
    host="${IPA_HOSTNAME%.}."
    if is_dry_run || is_check; then
        plan "create/update only integrated reverse zone $reverse_zone and PTR $reverse_record -> $host"
        return 0
    fi
    ipa dnszone-show "$reverse_zone" >/dev/null 2>&1 || run_command ipa dnszone-add "$reverse_zone"
    if ! ipa dnsrecord-show "$reverse_zone" "$reverse_record" >/dev/null 2>&1; then
        run_command ipa dnsrecord-add "$reverse_zone" "$reverse_record" --ptr-rec="$host"
    fi
    state_set INTEGRATED_REVERSE_ZONE "$reverse_zone"
    state_mark_resource "dns-zone-$reverse_zone" created-by-bootstrap
}
